### ISSUE TITLE
Create Panini$Root interface for generated artifacts annotated with @Root

### ISSUE THREAD

**Issue by TErenberger** [hridesh/panini#116]
This would allow the CapsuleSystem.start() to use Class<? extends Panini$Root> which further limits the acceptable parameters from classes that extend Panini$Capsule (with or without @Root) to only those annotated with @Root. 

This interface could be blank or it could contain a method that would take the place of how public static void main is used on generated capsules. This is useful as it separates a java convention (main) from a panini convention (root).

**Comment by dwtj** [comment]
Good idea!

**Comment by dwtj** [comment]
Closed by PR #114.
