### ISSUE TITLE
[capsule-generation/*] Need to generate both active and passive capsules

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#14]
Original by dwtj at: https://github.com/dwtj/panini/issues/27

What are the differences between active and passive capsule? What parts of the capsule generation process need to be handled differently, depending on whether the capsule being generated is active or passive. One obvious example is the `run()` method: in the case of passive capsules, we need to auto-generate a run method which unpacks ducks (and other messages) and handles them appropriately; in the case of active capsules, the user-defined `run()` method needs to be delegated to.

What other differences are there? Do we even need the queue on active capsules? Maybe. I'm not sure. Maybe active capsules need the queue in order to handle messages other than ducks (e.g. shutdown and terminate). If we don't need the queue, then should active capsules with the `Thread` execution profile actually inherit from some different class than `Capsule$Thread`?

If indeed there are many differences, then we should consider carefully how we separate and organize passive-related code from active-related code. (The creation of another `Make*` class may be one way.)

**Comment by dwtj** [comment]
These questions may be relevant to #77.

**Comment by dwtj** [comment]
I think the current code has had these questions solved for a while now. While it's arguable that the current code could be improved to better separate these concerns, I'm closing this issue because we have the functionality which we need for now.
