### ISSUE TITLE
[pipeline-refactor] Rules for @Future and @Block

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#15]
The `@Future` and `@Block` are annotations that can be added to a Capsule's procedure in order to explicitly state that you want to return a `java.util.concurrent.Future` or you want the procedure to block until the value is obtained.

1. A procedure cannot be annotated with both `@Future` and `@Block`
2. Reserved declarations (`run`, `design`, `init`) cannot be annotated with `@Future` or `@Block`
3. Private capsule methods cannot be annotated with `@Future` and `@Block`
4. Procedures on signatures can be annotated with `@Future` and `@Block` - any class that implements the signature and it's procedures does not need to annotate with `@Future` or `@Block`
5. Procedures which return a Final type will by default block
6. Procedures which return a Primitive type will by default block
7. Procedures which return a type with a final method will by default block
7. A Procedure which returns a primitive type and has an `@Future` annotation must autobox the result in order to Futureize it

If a Procedure returns a type which cannot be converted into to a Duck Future, then it will block by default and throw a compiler warning.

**Comment by dwtj** [comment]
This functionality was merged at some point over the psat summer.
