### ISSUE TITLE
Add Basic Static Syntax Checks

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#52]
These should be simple check that we can do through the annotation processor

**Comment by dwtj** [comment]
One recent suggestion from Dr. Rajan, was to look into whether either the Dataflow Framework or the Checker Framework could be useful to us for this.

**Comment by dwtj** [comment]
Though we might want some static checks which will need information from within procedure bodies, for the v0.1.0 milestone and this issue, we are only going to implement those checks which can be performed via the annotation processing interface (i.e. by inspecting capsule interfaces).

**Comment by dwtj** [comment]
Note that as of commit  9544250ac9b91eb54644ee1491424ddc69bdd03b, our checking infrastructure within `org.paninij.proc.check` does not crash a build when an error is found (i.e. when a check fails).

**Comment by dwtj** [comment]
The first pass at the three primary kinds of checks has been added as of commit 730afc33bfb808701d168416adc6561c93756b93.

- Capsule template checks.
- Signature template checks.
- Duckability checks.
