### ISSUE TITLE
Document Runtime Package

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#53]
Runtime package will be the most used/accessed package and can serve as the main point of documentation for users

**Comment by dwtj** [comment]
We should decide on which classes and packages warrant this in-depth documentation. As a first approximation, I would say that we should do everything in `org.paninij.lang`.

**Comment by dwtj** [comment]
A decent first draft of this has been merged as part of #117, but there may be a bit more to do. In particular, `@Root` needs a bit of a description. What else in the `org.paninij.lang` package needs doing?

**Comment by dwtj** [comment]
Is a complete first draft of the `org.paninij.lang` documentation finished as of commit aa765822e503c897f7ce42246902e5c335af0140? Can this issue be closed?

**Comment by ddmills** [comment]
Yes, my bad, I forgot to close it. This issue closed as of aa76582
