### ISSUE TITLE
Check that CapsuleTemplate procedures are not variadic

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#60]
Variadic procedures are currently illegal

**Comment by dwtj** [comment]
I think this should be rolled into issue #52.

**Comment by dwtj** [comment]
Note that the recent commit 9544250ac9b91eb54644ee1491424ddc69bdd03b does not check for variadic procedures; it checks for variadic methods more generally. That includes declarations such as `init()`, `design()`, and `run()`. Is this sufficient for now or should we make this more precise? Should we make this declarations non-variadic for now as well?

**Comment by dwtj** [comment]
This check needs an associated test or two. See issue #54.

**Comment by dwtj** [comment]
Closed by b68b47b8fb11ca594e48fc86f23713e6bf030c68.
