### ISSUE TITLE
Check that a CapsuleTemplate does not contain a constructor

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#69]

**Comment by dwtj** [comment]
I think this should be rolled into issue #52.

**Comment by dwtj** [comment]
This check needs a test or two. See Issue #54.

**Comment by dwtj** [comment]
The check added in commit 3ffa3423d3258b45f8d68e2ed6ed57055097b2e1 does not quite satisfy the intended check. It checks that any constructor defined within a capsule template has zero arguments.

Ideally, we would be checking that there are no constructors except for the implicit default constructor. However, I don't know how to use the `javax.lang.model` API to differentiate between an implicit default constructor and some user-defined zero-arg constructor.

**Comment by dwtj** [comment]
Closed by b68b47b8fb11ca594e48fc86f23713e6bf030c68.
