### ISSUE TITLE
Check that a CapsuleTemplate has a well-formed init(), if any

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#70]
a well-formed init: 

`public void init() { .. }`

or maybe

`private void init() { .. }`

**Comment by dwtj** [comment]
I think this should be rolled into issue #52.

**Comment by dwtj** [comment]
Work has been started on this, but I still need to double check what the exact criteria are for an `init()` being well-formed. Can it take arguments? Is it able to be public?

**Comment by dwtj** [comment]
Closed by 090172f67862a524ea2295b7a67bd82db57a1457.
