### ISSUE TITLE
Generated Capsules: Conditions About Whether a Capsule Needs a `main()` Method Are Too Naive

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#8]
Original issue created by dwtj at: https://github.com/dwtj/panini/issues/42

As of commit f722f959822812fbecf2fc28affee2bae8fdc0ce, `main()` methods are added to every capsule which is both active and has no @Wired capsules. (In that commit, the term "root" capsule was used to refer to capsules which met *both* of these conditions.) However, there are examples which demonstrate that these are not sufficient criteria for determining whether a capsule needs a `main()` method.

Consider a passive capsule type named `Supervisor` with five child capsule fields, each of type `Worker`. Suppose that

- The `Supervisor` is passive.
- The `Supervisor` wires itself into each of the five `Worker` capsules.
- Each `Worker` is active.

In this case, the user should be able to start up an instance of a `Supervisor`, so a `Supervisor` *should* have a `main()`. However, if we use the current naive criteria, the `Supervisor` is *not* given a `main()` method.

I'm not exactly sure about the right way to solve this in general. But ideally, we want a solution which is defined modularly. By this I mean that we should be able to determine whether a given capsule type needs a `main()` from just the capsule implementation and the interfaces of the capsules to which it has references.

Are there any simple workarounds that we could use to fix this problem. For example, could we use the current naive criteria but then allow the user to use some sort of syntax to opt-into the inclusion of a `main()` method (e.g. with an annotation or an argument to the `@Capsule` annotation).

**Comment by ddmills** [comment]
Commit b181eedc9b7c53b7f5722b62ded86fe329dd6790 contains more information and a potential solution to this issue

**Comment by dwtj** [comment]
Resolved by our introduction of `@Root`. See #89 and #90 for more info.
